# Generated by Django 4.2.7 on 2024-03-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
