# Generated by Django 5.0.3 on 2024-03-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to='user.user')),
                ('following', models.ManyToManyField(blank=True, related_name='following', to='user.user')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
