# Generated by Django 4.2.7 on 2024-03-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='follower',
        ),
    ]
